### ISSUE TITLE
Use YouTube search if not found

### ISSUE THREAD

**Issue by aryaoffixial** [acszo/Redomi#3]
### Feature description

Suppose someone choosed youtube as link opening shortcut, but by chance the link recently converted isn't available on YouTube or YouTube music. So then the app will show search button & if i click there the song meta tags will automatically searched on YouTube app 
```https://m.youtube.com/results?sp=mAEA&search_query=```

Thank you ✨

### Why do you want it?

I'm too lazy to manually open an app and copy paste or type the song metadata.

### Additional context

I hope it will not be a boring idea.

**Comment by acszo** [comment]
Clever idea, It's a good fallback solution. Also when sharing, it could be of good use, if it happens that it doesn't find the result for that one app you need, you just share the query instead of typing the song's name in chat to someone, and both benefit from it. I'll need to check out for the other platforms how they query and if they open in app. Thanks

**Comment by acszo** [comment]
Clever idea, It's a good fallback solution. I'll add a button called "Search" or "Search on Youtube" when no result is found after opening a link. Thanks for the suggestion

**Comment by aryaoffixial** [comment]
Thanks captain 🩶🔥
